apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    name: dev
spec:
  containers:
    - name: keerthi-container
      image: nigelpoulton/pluralsight-docker-ci:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080
